### ISSUE TITLE
ERROR [ExceptionHandler] : No settings.json file found

### ISSUE THREAD

**Issue by zarevskaya** [Arthi-chaud/Meelo#686]
**Describe the bug**
Hi, when I run docker-compose, I get this error:

meelo-server-1:
![Screenshot_20240707_160429](https://github.com/Arthi-chaud/Meelo/assets/60230221/e398dccf-1ea8-4aa3-967b-7639224b3599)

**To Reproduce**
Run the docker-compose. (.env +settings.json  configured)

**Screenshots**
![Screenshot_20240707_160346](https://github.com/Arthi-chaud/Meelo/assets/60230221/7283e10c-07ec-44a3-9ee6-4b3bed08f6d2)

**Version**
the latest version of the application

Merci d'avance!

**Comment by Arthi-chaud** [comment]
Hi! thanks for your issue!
We have 2 problems here:

Regarding the 'settings file not found error', did you set the `CONFIG_DIR` environment value to the directory that contains the `settings.json` ? (The documentation may be misleading)

About the meilisearch error, it happens from time to time. When that happens, restart the containers.
Hope this helps!

**Comment by zarevskaya** [comment]
Thanks, for a part, now I have this error there and for I put, to test:

# Random String used to sign JWT Tokens
JWT_SIGNATURE=1010101011101110
# Key used to authenticate the Meilisearch Instance
# Should be a random string, must be at least 16 bytes
MEILI_MASTER_KEY=1010101011101110


ERROR [ExceptionHandler] : Settings File: missing field 'apiKey'

Any hit?

**Comment by Arthi-chaud** [comment]
Yup, this is another documentation error, my bad. In the `settings.json` file, set the "providers" value to `{}`. This error happens because the genius provider expects an API key.

**Comment by zarevskaya** [comment]
Thanks, je corrige!

**Comment by Arthi-chaud** [comment]
Let me know if it works for you, I'll close this issue when everything works as expected. A PR has been opened to fix the documentation errors you encountered :)

**Comment by zarevskaya** [comment]
Like this? 
![Screenshot_20240707_170950](https://github.com/Arthi-chaud/Meelo/assets/60230221/c1ba6ec5-de91-4ed6-b61e-a6137c22cbc4)

ERROR [ExceptionHandler] : Invalid Settings File

Sorry I'm not familiar with this part.

**Comment by Arthi-chaud** [comment]
Instead of
```json
"providers": {
  "genius": false,
  "musicbrainz": false,
},
```
it should be:
```json
"providers": {
  "musicbrainz": {},
},
```

**Comment by zarevskaya** [comment]
It's progressing, I no longer have any errors anywhere, but I can't access your application page.
All containers are without error. Weird.

Maybe an error here? But I don't see where.
![Screenshot_20240707_175125](https://github.com/Arthi-chaud/Meelo/assets/60230221/25b0b075-c2b0-40e8-b0b8-236f783831ef)

**Comment by Arthi-chaud** [comment]
> Wouldn't it be simpler to add container_name: postgres in the docker-compose.yml?
This will be done in [this PR](https://github.com/Arthi-chaud/Meelo/pull/687)

The PUBLIC_SERVER_URL should be `http://192.168.1.152/api`. (It should be the URL to the server/api, not the webapp. The `/api` is from the nginx template)

**Comment by zarevskaya** [comment]
Unable to reach the application via the web page.

![Screenshot_20240707_183852](https://github.com/Arthi-chaud/Meelo/assets/60230221/9b11c6d1-d05a-40f6-82c3-028033b2cd4e)

Soooo weird.
No error logs. But it does not work. Here.

**Comment by Arthi-chaud** [comment]
Did you download and put the `nginx.conf.template` file in the same directory as the `docker-compose` file

**Comment by zarevskaya** [comment]
Yes :)

`/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration

/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/

/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh

10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf

10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf

/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh

/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh

/docker-entrypoint.sh: Configuration complete; ready for start up

2024/07/07 16:36:55 [notice] 1#1: using the "epoll" event method

2024/07/07 16:36:55 [notice] 1#1: nginx/1.24.0

2024/07/07 16:36:55 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 

2024/07/07 16:36:55 [notice] 1#1: OS: Linux 6.1.0-21-amd64

2024/07/07 16:36:55 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576

2024/07/07 16:36:55 [notice] 1#1: start worker processes

2024/07/07 16:36:55 [notice] 1#1: start worker process 32

2024/07/07 16:36:55 [notice] 1#1: start worker process 33

2024/07/07 16:36:55 [notice] 1#1: start worker process 34

2024/07/07 16:36:55 [notice] 1#1: start worker process 35`

**Comment by zarevskaya** [comment]
it will be nammed: nginx.conf.template or nginx.conf? In both cases I have no success.

**Comment by Arthi-chaud** [comment]
There should be WAY more logs than this. 

It should be named `nginx.conf.template`

Please, can try:

- `docker-compose down --volumes`
- Comment out the following lines in the `server` section
```yaml
 meilisearch:
   condition: service_healthy
```

**Comment by zarevskaya** [comment]
Aaaaaaaaaaaaaaaah, youpie!!!!!! 
![Screenshot_20240707_191125](https://github.com/Arthi-chaud/Meelo/assets/60230221/ed99cf56-b15c-45fb-92d1-ed23d03ec189)

That work!!!! Thank you for your patience but I did everything I could.

**Comment by Arthi-chaud** [comment]
Awesome!
Thanks for your patience!

Shall I close the issue ?

**Comment by zarevskaya** [comment]
Yup, thanks again!!!
