### ISSUE TITLE
I can't see my sent files.

### ISSUE THREAD

**Issue by zarevskaya** [Arthi-chaud/Meelo#688]
**Describe the bug**
Hi!

When I press F5 I briefly see, I think, my files, but then it's empty.

I did: chown 1000:1000 data/
1000 is my ID.

**To Reproduce**

Send audio files to the data folder

**Version**
The latest version of the application.

**Comment by zarevskaya** [comment]
![Screenshot_20240707_193945](https://github.com/Arthi-chaud/Meelo/assets/60230221/79badcce-a3c0-4552-9f38-541071d98477)

**Comment by Arthi-chaud** [comment]
Hi!

What you see is just the loading state for the web app. It does not actually mean that files were scanned.
In the settings page, did you run a scan?
If you did, what do the server's logs say? Also, how are your files organized?

**Comment by zarevskaya** [comment]
Oh... //data! 

It's probably my mistake!

![Screenshot_20240707_194347](https://github.com/Arthi-chaud/Meelo/assets/60230221/18edbb12-79f1-41c2-b07c-d6890efaa462)

**Comment by Arthi-chaud** [comment]
Yup, when you create your library, you should not include the /data. Instead, you should set the path to ./

**Comment by zarevskaya** [comment]
Ok, it's better, but I still can't see my music:

![Screenshot_20240707_194900](https://github.com/Arthi-chaud/Meelo/assets/60230221/c405b947-0d2d-4e1a-bb75-78dfdb0ae5f9)

**Comment by Arthi-chaud** [comment]
You should check out the recommended file structure [here](https://arthi-chaud.github.io/Meelo/setup/prepare-music-library/)

**Comment by zarevskaya** [comment]
Unfortunately it's not necessarily music that comes from albums. It is therefore impossible for me to use it.

**Comment by Arthi-chaud** [comment]
I didn't consider this usecase. I just opened an issue about it.

**Comment by zarevskaya** [comment]
Thanks a lot!! :)

**Comment by Arthi-chaud** [comment]
Did you manage to use the workaround?
If you can't use it, I will close this issue in favour of #689

**Comment by zarevskaya** [comment]
Hey, not really. The result is random.  I mean there are albums it doesn't detect. Thanks 👍

**Comment by zarevskaya** [comment]
![Screenshot_20240708_142139](https://github.com/Arthi-chaud/Meelo/assets/60230221/9f30398d-eda7-4d32-99bd-58d947232290)

Victory!

**Comment by zarevskaya** [comment]
The french tutorial:

https://belginux.com/installer-meelo-avec-docker/
